import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({subsets:["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className}`}
      >
        <div className={"@container px-[20px] md:px-[50px] lg:px-[100px] text-[16px] lg:text-[20px]"}>
            {children}
        </div>
      </body>
    </html>
  );
}
